### ISSUE TITLE
Force obscure credentials

### ISSUE THREAD

**Issue by marjatech** [newhinton/round-sync-documentation#1]
Using Passwords longer than 22 chars and consisting only of base64 chars leads to it beeing stored unobscured because rclone thinks it might me obscured already.

That leads to authentication failures then.

From the Docs:
`NB If the password parameter is 22 characters or longer and consists only of base64 characters then rclone can get confused about whether the password is already obscured or not and put unobscured passwords into the config file. If you want to be 100% certain that the passwords get obscured then use the --obscure flag`

**Comment by marjatech** [comment]
Wrong repo, sorry

**Comment by newhinton** [comment]
This is also a known issue ;) It is already solved in the current master branch, but thanks for reporting :D You are also the first one to actually name the root-cause directly and not only symptoms
